caldera_criticalmass_tips_index:
    path:     /
    defaults: { _controller: CalderaCriticalmassTipsBundle:Default:index }

caldera_criticalmass_tips_city:
    path:     /{citySlug}
    defaults: { _controller: CalderaCriticalmassTipsBundle:Default:index }
