parameters:
#    caldera_criticalmass_one.example.class: Caldera\Bundle\CriticalmassOneBundle\Example

services:
#    caldera_criticalmass_one.example:
#        class: %caldera_criticalmass_one.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
